version: "3.6"

services:
  timescaledb1:
    build: ./timescaledb
    container_name: scale_db_01
    volumes:
        - ./timescaledb/conf/patroni.yml:/etc/patroni.yml
    #   - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - timescaledb_cluster
    depends_on:
      - etcd

  timescaledb2:
    build: ./timescaledb
    container_name: scale_db_02
    volumes:
        - ./timescaledb/conf/patroni2.yml:/etc/patroni.yml
    #   - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - timescaledb_cluster
    depends_on:
      - etcd

  timescaledb3:
    build: ./timescaledb
    container_name: scale_db_03
    volumes:
        - ./timescaledb/conf/patroni3.yml:/etc/patroni.yml
    #   - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - timescaledb_cluster
    depends_on:
      - etcd

  etcd:
    image: 'bitnami/etcd:latest'
    container_name: scale_etcd
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - timescaledb_cluster
    volumes:
      - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml

  haproxy:
    image: haproxy:1.9.8-alpine
    container_name: scale_haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    ports:
      - 7000:7000
      - 5000:5000
    networks:
      - timescaledb_cluster

  grafana:
    image: grafana/grafana
    container_name: scale_monitor
    ports:
      - 5500:3000
    networks:
      - timescaledb_cluster
    depends_on:
      - haproxy

  zabbix:
    image: zabbix/zabbix-server-pgsql
    container_name: scale_zabbix
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=haproxy
      - DB_SERVER_PORT=5000
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - timescaledb_cluster
    depends_on:
      - haproxy

  zabbixweb:
    image: zabbix/zabbix-web-nginx-pgsql
    container_name: scale_zabbix_web
    ports:
      - 10080:8080
    environment:
      - ZBX_SERVER_HOST=zabbix
      - DB_SERVER_HOST=haproxy
      - DB_SERVER_PORT=5000
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - timescaledb_cluster
    depends_on:
      - zabbix

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on: 
      - haproxy
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

networks:
  timescaledb_cluster:
    driver: bridge
    name: timescaledb_cluster
